// Inspirational quotes shown on page load (js/quotes.js).
export const quotes = [
    "Believe you can and you're halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "You miss 100% of the shots you don't take.",
    "The only way to do great work is to love what you do.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Do something today that your future self will thank you for.",
    "You are never too old to set another goal or to dream a new dream.",
    "The best way to predict your future is to create it.",
    "You don't have to be great to start, but you have to start to be great.",
    "The biggest risk is not taking any risk.",
    "Don't be afraid to take the road less traveled.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "Happiness is not something ready made. It comes from your own actions.",
    "The best revenge is massive success.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to be great to start, but you have to start to be great.",
    "The biggest risk is not taking any risk.",
    "Don't be afraid to take the road less traveled.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "Happiness is not something ready made. It comes from your own actions.",
    "The best revenge is massive success.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "Happiness is not something ready made. It comes from your own actions.",
    "The best revenge is massive success.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "You are never too old to become younger.",
    "The most powerful weapon on earth is the human soul on fire.",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
    "You don't have to be defined or confined by your environment, by your family, by your circumstances.",
    "The best way to make your dreams come true is to wake up.",
    "You are not a victim, you are a volunteer.",
    "The most important thing in life is your inner peace.",
    "You can't pour from an empty cup. Take care of yourself first.",
    "The best time to make a change is when you're feeling stuck.",
    "You are the architect of your own destiny.",
    "Happiness is not something you find, it's something you create.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "The best revenge is to be unlike him who performed the injury.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "Do something wonderful, people may imitate it.",
    "You are the master of your destiny, the captain of your soul.",
    "The greatest wealth is to live content with little.",
    "You can't build a reputation on what you're going to do.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not a product of your circumstances. You are a product of your decisions.",
    "The most important thing in life is to learn how to give out love, and let it come in.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "The biggest mistake you can make is fearing that you'll make one.",
    "Do something today that will make your future self proud.",
    "You can't go back and change the beginning, but you can start where you are and change the ending.",
    "The best way to find yourself is to lose yourself in the service of others.",

];

export function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return "Daily Thought: \"" + quotes[randomIndex] + "\"";
}
